vivox9:
  size: 1080x1920
  # 红色可抢
  color_true: (229, 53, 62)
  # 红包记录的位置
  pos_status: (887, 789)
  # 投票按钮
  pos_submit: (533, 1400)
  # 空白退出
  pos_other: (1052, 846)

realmeq3pro:
  size: 1080x2400
  # 红色可抢
  color_true: (229, 53, 62)
  # 红包记录的位置
  pos_status: (833, 833)
  # 投票按钮
  pos_submit: (533, 1400)
  # 空白退出
  pos_other: (900, 1700)
  # 缩小显示
  resize: 3
  # 月票
  pos_month: (96, 450)
  # 推荐票
  pos_recommend: (315, 453)

device_type: realmeq3pro
debug: false
sleep_ms: 500